a=[1,2,3,4]
b=[2,3,4,5]

In [6]:
ab=[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [2]:
import numpy as np

In [8]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

# NumPy Array'i Oluşturmak

In [10]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [11]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [12]:
np.array([3.14,4,2,13], dtype="int")

array([ 3,  4,  2, 13])

In [ ]:
#Sıfırdan array oluşturma

In [14]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3,5),dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [19]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [21]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.random.normal(10,4,(3,4))

array([[10.69843314, 13.10362403,  7.78956252,  9.15204165],
       [16.3160647 ,  2.92703167,  6.53724291,  5.43685052],
       [12.43558938,  8.53720186, 13.40998053, 10.43198736]])

In [24]:
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [9, 9, 8],
       [0, 4, 5]])

# Özellikleri

* **ndim**: _Boyut Sayısı_
* shape: Boyut Bilgisi
* size: Toplam Eleman Sayısı
* dtype: array veri tipi

In [25]:
np.random.randint(10, size=10)

array([5, 3, 5, 5, 6, 7, 5, 3, 3, 6])

In [ ]:
a=np.random.randint(10, size=10)

In [26]:
a.ndim

1

In [27]:
a.shape

(5,)

In [28]:
a.size

5

In [29]:
a.dtype

dtype('int32')

In [30]:
b=np.random.randint(10,size=(3,5))

In [31]:
b

array([[9, 9, 3, 1, 3],
       [4, 5, 4, 6, 6],
       [8, 5, 3, 1, 3]])

In [32]:
b.ndim

2

In [33]:
b.size

15

In [34]:
b.shape

(3, 5)

In [36]:
b.dtype

dtype('int32')

# Yeniden Şekillendirme(reshaping)

In [37]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
a.ndim

1

In [ ]:
#tek boyutlu array vektör, iki boyutlu array matris

# Array Birleştirme(Concatenation)

In [48]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [50]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [51]:
z=np.array([7,8,9])

In [52]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#İki boyut

In [54]:
a=np.array([[1,2,3],
            [4,5,6]])

In [55]:
np.concatenate([a,a])#default axis değeri 0 dır

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [56]:
np.concatenate([a,a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Ayırma

In [58]:
x=np.array([1,2,3,99,99,3,2,1])

In [59]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [60]:
a,b,c = np.split(x,[3,5])

In [61]:
a

array([1, 2, 3])

In [62]:
b

array([99, 99])

In [63]:
c

array([3, 2, 1])

In [ ]:
#İki Boyutlu ayırma

In [65]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [69]:
ust, alt=np.vsplit(m,[2])

In [70]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [71]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
sag, sol=np.hsplit(m, [2])

In [77]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [78]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama(Sorting)

In [4]:
v=np.array([0,5,68,63,1])
v

array([ 0,  5, 68, 63,  1])

In [5]:
np.sort(v)

array([ 0,  1,  5, 63, 68])

In [6]:
v

array([ 0,  5, 68, 63,  1])

In [7]:
v.sort()

In [8]:
v

array([ 0,  1,  5, 63, 68])

In [ ]:
#İki boyutlu sıralama

In [12]:
m=np.random.normal(20,5,(3,3))

In [14]:
m

array([[22.44517043, 20.30325767, 18.6787117 ],
       [19.42103925, 24.89167355, 20.30201357],
       [23.77410161, 18.63735455, 23.03960904]])

In [18]:
np.sort(m,axis=1)
#satırları sıralamak için

array([[18.6787117 , 20.30325767, 22.44517043],
       [19.42103925, 20.30201357, 24.89167355],
       [18.63735455, 23.03960904, 23.77410161]])

In [19]:
np.sort(m,axis=0)
#sütunları sıralamak için

array([[19.42103925, 18.63735455, 18.6787117 ],
       [22.44517043, 20.30325767, 20.30201357],
       [23.77410161, 24.89167355, 23.03960904]])

# Index ile Elemanlara Erişmek

In [1]:
import numpy as np
a=np.random.randint(10,size=10)
a

array([0, 0, 1, 1, 1, 7, 9, 4, 6, 7])

In [5]:
a[0]

5

In [6]:
a[-1]

1

In [7]:
a[0]=100
a

array([100,   9,   8,   4,   2,   1,   8,   2,   6,   1])

In [14]:
m=np.random.randint(10,size=(3,5))
m

array([[2, 5, 3, 0, 5],
       [5, 4, 6, 5, 5],
       [9, 3, 6, 1, 4]])

In [15]:
m[0,0]

2

In [16]:
m[1,1]

4

In [18]:
m[1,1]=150
m[1,1]

150

In [19]:
m

array([[  2,   5,   3,   0,   5],
       [  5, 150,   6,   5,   5],
       [  9,   3,   6,   1,   4]])

In [25]:
m[1,4]=600.50

In [26]:
m

array([[  2,   5,   3,   0,   5],
       [  5, 150,   6,   5, 600],
       [  9,   3,   6,   1,   4]])

In [6]:
ab=[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [2]:
import numpy as np

In [8]:
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

# Slicing ile elemanlara erişmek

In [2]:
import numpy as np

In [4]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
a[0:3]

array([20, 21, 22])

In [10]:
a[:3]

array([20, 21, 22])

In [11]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [12]:
a[1::2]

array([21, 23, 25, 27, 29])

In [15]:
a[2::2]

array([22, 24, 26, 28])

In [ ]:
#iki boyutlu slice işlemleri

In [18]:
m=np.random.randint(10,size=(5,5))
m

array([[5, 0, 5, 4, 1],
       [4, 9, 0, 4, 6],
       [4, 9, 2, 3, 6],
       [5, 7, 4, 7, 7],
       [0, 2, 1, 1, 7]])

In [20]:
m[:,0]#sütun seçme

array([5, 4, 4, 5, 0])

In [21]:
m[0,:]#satır seçme

array([5, 0, 5, 4, 1])

In [22]:
m[0]

array([5, 0, 5, 4, 1])

In [24]:
m[0:2, 0:3]#satır ve sütun ortak

array([[5, 0, 5],
       [4, 9, 0]])

In [25]:
m[::,:2]

array([[5, 0],
       [4, 9],
       [4, 9],
       [5, 7],
       [0, 2]])

In [26]:
m[1:3,:2]

array([[4, 9],
       [4, 9]])

# Alt Küme üzerinden işlem yapmak

In [2]:
import numpy as np
a=np.random.randint(10, size=(5,5))
a

array([[7, 8, 0, 9, 0],
       [9, 8, 6, 2, 4],
       [5, 0, 7, 9, 7],
       [0, 3, 2, 0, 1],
       [5, 0, 4, 6, 5]])

* Alt küme işlemlernin ana kümeyi de etkilediği durum

In [4]:
alt_a=a[0:3, 0:2]
alt_a

array([[7, 8],
       [9, 8],
       [5, 0]])

In [5]:
alt_a[0,0]=999
alt_a[1,1]=323
alt_a

array([[999,   8],
       [  9, 323],
       [  5,   0]])

In [6]:
a


array([[999,   8,   0,   9,   0],
       [  9, 323,   6,   2,   4],
       [  5,   0,   7,   9,   7],
       [  0,   3,   2,   0,   1],
       [  5,   0,   4,   6,   5]])

* Alt küme işlemlerinin ana kümeyi etkilememesi için :::

In [7]:
m=np.random.randint(10, size=(5,5))
m

array([[5, 8, 3, 7, 0],
       [0, 0, 2, 5, 0],
       [3, 0, 4, 2, 3],
       [6, 5, 9, 1, 7],
       [2, 1, 2, 9, 9]])

In [9]:
alt_b=m[0:3,0:2].copy()
#copy() alt kümeyi ana kümeden bağımsızlaştırır.
alt_b

array([[5, 8],
       [0, 0],
       [3, 0]])

In [11]:
alt_b[0,0]=999999
alt_b

array([[999999,      8],
       [     0,      0],
       [     3,      0]])

In [12]:
m

array([[5, 8, 3, 7, 0],
       [0, 0, 2, 5, 0],
       [3, 0, 4, 2, 3],
       [6, 5, 9, 1, 7],
       [2, 1, 2, 9, 9]])

# Fancy Index ile elemanlara erişmek
* ÇOK ÖNEMLİ

In [13]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
v[1]

3

In [15]:
v[5]

15

In [17]:
[v[1],v[5]]

[3, 15]

In [18]:
al_getir=[1,3,5]

In [19]:
v[al_getir]
#Fancy budur.

array([ 3,  9, 15])

In [ ]:
#İki boyutta fancy

In [22]:
m= np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
satir= np.array([0,1])
sutun=np.array([1,2])

In [26]:
m[satir,sutun]

array([1, 5])

In [ ]:
# basit index ile fancy index

In [27]:
m[0,[1,2]]

array([1, 2])

In [ ]:
#slice ile fancy

In [28]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [29]:
v=np.array([1,2,3,4,5])

In [30]:
v>5

array([False, False, False, False, False])

In [32]:
v>0

array([ True,  True,  True,  True,  True])

In [33]:
v[v<3]
#fancy

array([1, 2])

In [34]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [35]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [36]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [38]:
v*4

array([ 4,  8, 12, 16, 20])

# Matematiksel İşlemler

In [2]:
import numpy as np
v=np.array([1,2,3,4,5])

In [ ]:
#matematiksel işlemler yapılırken UFUNC adı verilen fonksiyonlar çalışır.

In [3]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [4]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [ ]:
np.multiply(v,4)

In [8]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [ ]:
#v%3=np.mod(v,3)
#v**=np.power(v,2)

In [11]:
np.absolute(np.array([-1]))

array([1])

In [12]:
np.sin(360)

0.9589157234143065

In [13]:
np.cos(180)

-0.5984600690578581

In [14]:
v=np.array([1,2,3])

In [15]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [16]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [ ]:
#cheatsheet pyhton library leri için arama yaparken arama sonunda bunu koyarsak, düzgün bir format ile konu anlatımı bulabiliriz.

# Numpy ile 2 boyutlu denklem çözme

5*x0+x1=12

x0+3*x1=10

In [20]:
#Üstteki denklemin numpy'da tanımlanması
a=np.array([[5,1],[1,3]])
b=np.array([12,10])

In [21]:
a

array([[5, 1],
       [1, 3]])

In [22]:
b

array([12, 10])

In [23]:
x=np.linalg.solve(a,b)
x
# x0 ve x1 değerlerini bulur.

array([1.85714286, 2.71428571])